saving and experiment set up
pepijnbruinaars/MAIR-G14 pull request #66
Opened 2023-10-20 13:13 UTC by davidhuizinga

2023-10-23 11:23 UTC, pepijnbruinaars requested changes
Looks good for the most part, left a few inline comments with Milo.

On a general note, I think we should decrease the task count per gendered voice to 5 instead of 10. It seems a bit much to me, and I wouldn't voluntarily want to have 20 conversations with some random chatbot lol.

2023-10-24 15:29 UTC, davidhuizinga commented on src/dialog_manager.py
> +        first_gender = input("Do you want to start with male or female? enter \"m\" or \"f\": ")
I think this correctly implements a predetermined order for group A and group B:
group A gets first 5 male then 5 female
group B gets first 5 female then 5 male
so when we all interview four people we have to select the male John for 2 of them and Jane for the other 2. 
Was this what we discussed during the workgroup? I'm not sure anymore lol

2023-10-24 15:39 UTC, Milooooo1 approved these changes
Looks good let start the experiments :)

2023-10-24 15:41 UTC, Milooooo1 approved these changes
Looks good lets start experimenting :)

2023-10-24 15:58 UTC, pepijnbruinaars commented on src/dialog_manager.py
> +            if(self.dialog_config["experiment"] == False):
Just a minor remark, doesn't matter that match, but it's more concise to write this as `if not self.dialog_config["experiment"]:`

2023-10-24 15:59 UTC, pepijnbruinaars approved these changes
Let's go!

2023-10-24 15:59 UTC, merged